### ISSUE TITLE
Explicitly describe what the starting code should do

### ISSUE THREAD

**Issue by roryokane** [kata-seeds/kata-seeds.github.io#1]
On Lobsters, @justincampbell [wrote](https://lobste.rs/s/etepb5/kata_seeds/comments/5qixto#c_5qixto):

> The person greeting is intentionally simple and vague so that it doesn’t lead you down a path.

This is the only place I have seen a description of what the code in a template should do – “person greeting”. There is no mention of the expected functionality on [the website](http://kata-seeds.github.io/) or in [the template](https://github.com/kata-seeds/kata-seed-template).

Writers of new seeds can guess what the starting code is supposed to do by looking at a bunch of other seeds, but I think it would reassure them to also have explicit instructions somewhere. You might use this paragraph:

> The code in the seed should implement a simple way to greet a person, plus a test that it works. Implement that functionality in whatever way is most natural in your language. To get an idea of how small the implementation should be, you should read the implementations in a few seeds that use similar languages to yours.

**Comment by justincampbell** [comment]
:+1: paragraph is perfect
